language: cpp
compiler:
  - gcc

before_script:
# setting up bam
  - git clone git://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..
# install something
  - sudo apt-get install libmysqlclient-dev

script:
  - bam/bam -s compile.lua